
const state={heroes:[],filters:{classe:null,rarete:null,source:null,faction:null},sort:'added',search:''};
const $=s=>document.querySelector(s);const $$=s=>document.querySelectorAll(s);
function unique(arr){return [...new Set(arr.filter(Boolean))].sort((a,b)=>a.localeCompare(b,'fr'));}
function makePills(id,items,key){const box=$(id);box.innerHTML='';items.forEach(item=>{const b=document.createElement('button');b.className='pill';b.textContent=item;b.onclick=()=>{state.filters[key]=state.filters[key]===item?null:item;renderPills();renderHeroes();};box.appendChild(b);});}
function renderPills(){ $$('.pill').forEach(p=>p.classList.toggle('active',Object.values(state.filters).includes(p.textContent))); $$('.sort').forEach(b=>b.classList.toggle('active',b.dataset.sort===state.sort)); }
function heroMatches(h){const s=state.search.toLowerCase();return (!s||h.nom.toLowerCase().includes(s))&&(!state.filters.classe||h.classe===state.filters.classe)&&(!state.filters.rarete||h.rarete===state.filters.rarete)&&(!state.filters.source||h.source===state.filters.source)&&(!state.filters.faction||h.faction===state.filters.faction||h.double_faction===state.filters.faction);}
function renderHeroes(){let list=state.heroes.filter(heroMatches);if(state.sort==='az')list.sort((a,b)=>a.nom.localeCompare(b.nom,'fr'));if(state.sort==='eval')list.sort((a,b)=>b.evaluation-a.evaluation);if(state.sort==='rarete')list.sort((a,b)=>a.rarete.localeCompare(b.rarete,'fr'));$('#heroCount').textContent=list.length;const grid=$('#heroesGrid');grid.innerHTML='';list.forEach(h=>{const tpl=$('#heroTemplate').content.cloneNode(true);tpl.querySelector('.hero-image').textContent=h.nom[0];tpl.querySelector('h3').textContent=h.nom;tpl.querySelector('.meta').textContent=`${h.classe} • ${h.faction}${h.double_faction?' / '+h.double_faction:''}`;tpl.querySelector('.score').textContent=`Évaluation globale : ${h.evaluation}/50`;tpl.querySelector('.notes').innerHTML=`<span class="note">Dragon ${h.notes.dragon}</span><span class="note">Titan ${h.notes.titan}</span><span class="note">Donjon 1 ${h.notes.donjon_1}</span><span class="note">GvG ${h.notes.gvg}</span>`;grid.appendChild(tpl);});}
fetch('data/heros.json').then(r=>r.json()).then(data=>{state.heroes=data;makePills('#classFilters',unique(data.map(h=>h.classe)),'classe');makePills('#rarityFilters',unique(data.map(h=>h.rarete)),'rarete');makePills('#sourceFilters',unique(data.map(h=>h.source)),'source');makePills('#factionFilters',unique(data.flatMap(h=>[h.faction,h.double_faction])),'faction');renderPills();renderHeroes();});
$('#searchInput').addEventListener('input',e=>{state.search=e.target.value;renderHeroes();});$$('.sort').forEach(b=>b.onclick=()=>{state.sort=b.dataset.sort;renderPills();renderHeroes();});
